language: ruby
rvm:
  - "2.1.0"
  - "2.1.1"
  - "2.1.2"
  - "2.1.3"
  # - jruby-19mode # JRuby in 1.9 mode
  # - rbx
env:
  - NO_BROWSER=true
  - BROWSER=sauce OS="Windows 8" USE_BROWSER="Firefox" VERSION="33"

script: bundle exec rake
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/046f551739ef8cf19b8c
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
